CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE,
    year_of_birth int NOT NULL
    )

CREATE TABLE Book(
   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   person_id int REFERENCES Person(id) ON DELETE SET NULL,
   title varchar NOT NULL,
   author varchar NOT NULL,
   year_of_publication int NOT NULL
)